### PR TITLE
Optimize boot time

### PR DESCRIPTION
**Pull request by marcusschmidt**
Among other things, each request causes the activated plugins to be booted, regardless of whether they are needed later or not. The necessity is not yet known at boot time.
For this reason it makes sense to keep booting a plugin as lean as possible.

The following diagram shows that the boot process of this plugin takes quite a long time in comparison (a payment plugin that boots twice as long as Ceres and IO together).

Bildschirmfoto 2019-10-07 um 16 32 39

When booting, the functions `register` and `boot` are called one after the other. However, it is noticeable that most of the time does not pass within these functions.
The next diagram shows that most of the time falls on the dependency injection of the `boot` function.

Bildschirmfoto 2019-10-09 um 10 26 28

I've done some optimizations here to instantiate objects not until they're actually needed. This is the result:

Bildschirmfoto 2019-10-09 um 10 50 09

### CODE REVIEW

**Comment by marcusschmidt** [comment]
Furthermore, the measurement results are not representative of the overall performance since they were not generated in a productive system. However, the relationship between the individual plug-ins can be seen from this.

**Comment by mkreusch** [comment]
Hi Marcus,

thanks for your contribution!
I would have thought that the loaded Objects were loaded at some point later anyway, thus not making a real difference in the end but that is something you certainly know better and I don't see a reason not to make these changes.
Do you care for having your commit directly pulled in and being mentioned as contributor? In this case, please, clean the code style changes (especially line breaks in the method argument lists). If not I'll just copy your code and format it myself.

Kind regards 
Marcus

**Comment by marcusschmidt** [comment]
Hello, Marcus,

I'd like to be part of the contributors, thank you for asking.

But first of all this change has still to be tested. I'm familiar with plugins in general, but not with individual plugins in particular, like this one. Can you please test my changes?

Kind regards
Marcus

**Comment by mkreusch** [comment]
Hi Marcus,

your changes passed all of our tests. Therefore I will be happy to pull it into the repository as soon as you adjusted the code style.

Thanks and best regards
Marcus

**Comment by marcusschmidt** [comment]
Hi @mkreusch,

I adjusted the code style.

Kind regards
Marcus

**Comment by mkreusch** [comment]
Thank you - there are just a few lines at the end of this file left and we are good to go:
`https://github.com/AlkimMedia/AmazonPay_Plenty/compare/master...marcusschmidt:optimize_boot_time#diff-6e1e9c5d589c050602cea414d5373860`

**Comment by marcusschmidt** [comment]
New line is gone now too, if that's what you meant 😉

**Comment by mkreusch** [comment]
Hi Marcus,

there are a few more new line breaks in that file but I will take care of this for to not make this overly complicated. Thanks a lot for your contribution!

Best regards
Marcus

**Pull request merged**
